import type { Metadata } from "next";
import type { ReactNode } from "react";
import {
  DM_Sans as DMSans,
  Lora as LoraFont,
  Work_Sans as WorkSans,
} from "next/font/google";
import "./globals.css";

import { SiteChrome } from "@/components/chrome/SiteChrome";

const dmSans = DMSans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

const workSans = WorkSans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-work-sans",
  display: "swap",
});

const lora = LoraFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${workSans.variable} ${lora.variable}`}
    >
      <body>
        <SiteChrome>{children}</SiteChrome>
      </body>
    </html>
  );
}
